#pragma config(Motor,  port1,           intake,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           left1,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           right1,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           left2,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           puncher1,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           puncher2,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           right2,        tmotorNone, openLoop)
#pragma config(Motor,  port8,           left3,         tmotorNone, openLoop)
#pragma config(Motor,  port9,           right3,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//--------------------------------------Driver control--------------------------------------------------------------
task main()
{
	//while driver control is active...
	while (true) {

	//DRIVE PROGRAM: right drive motors should be on ports 1, 2 and 3. Left drive motors should be set to 4, 5, and 6.

			//gets right stick input and drives right motors
			motor [right1] = vexRT[Ch2];
			motor [right2] = vexRT[Ch2];
			motor [right3] = vexRT[Ch2];

			//gets left stick input and drives left motors
			motor [left1] = vexRT[Ch3];
			motor [left2] = vexRT[Ch3];
			motor [left3] = vexRT[Ch3];
			}
}
