#pragma config(Motor,  port2,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightBack1,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftBack1,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           puncher,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           angleChanger,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightBack2,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           leftBack2,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*********************************************************************/
/*********************************************************************/
/*********************************************************************/

/** --------------------- 72832S competition ctrl -------------------*/

/*********************************************************************/
/*********************************************************************/
/*********************************************************************/

// Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#pragma systemFile

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

/*********************************************************************/
/*********************************************************************/
/*********************************************************************/

/** ---------------------- 72832S include files ---------------------*/

/*********************************************************************/
/*********************************************************************/
/*********************************************************************/

#include "include/jpearman/SmartMotorLib.c"

#include "BNSLibrary/BNSLib.h"

#include "Vex_Competition_Includes.c"  // Main competition background code...do not modify!

#include "include/mAPI.h"

/*********************************************************************/
/*********************************************************************/
/*********************************************************************/

/** ------------------------ 72832S pre auton -----------------------*/

/*********************************************************************/
/*********************************************************************/
/********************************************\*************************/

void pre_auton() {
    // Set bStopTasksBetweenModes to false if you want to keep user created tasks
    // running between Autonomous and Driver controlled modes. You will need to
    // manage all user created tasks if set to false.
    init();
}

task autonomous(){
    delay(4);

}

/*********************************************************************/
/*********************************************************************/
/*********************************************************************/

/** ------------------- 72832S opcontrol functions ------------------*/

/*********************************************************************/
/*********************************************************************/
/*********************************************************************/

task usercontrol() {

	stopTask(autonomous);

  // Define which motors are linked

  // Declare that you want the Library to keep a lid on the
  // motors by measuring the temperature of the PTC components
  SmartMotorPtcMonitorEnable();

  // Run smart motors
  SmartMotorRun();
  SmartMotorsInit();

  bLCDBacklight = true;                                    // Turn on LCD Backlight

  while (true) {
    opcontrol();
  }
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////
