////////////////////////////////////////////////////////////////////////////////////////

#pragma config(Sensor, in3, autonPotent, sensorPotentiometer)
#pragma config(Sensor, in4, ballIntake, sensorLineFollower)
#pragma config(Sensor, dgtl1, rightEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3, leftEncoder, sensorQuadEncoder)
#pragma config(Motor, port1, intake1, tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor, port2, left1, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port3, left2, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port4, left3, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port5, right3, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port6, right2, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port7, right1, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port8, noUse, tmotorNone, openLoop)
#pragma config(Motor, port9, puncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor, port10, intake2, tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////


// Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#pragma systemFile

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////

// SmartMotorLibrary
#include "jpearman/SmartMotorLib.c"

#include "Vex_Competition_Includes.c"  // Main competition background code...do not modify!

#include "src/init.c"

#include "src/auton.c"

#include "src/opcontrol.c"

/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton() {
    // Set bStopTasksBetweenModes to false if you want to keep user created tasks
    // running between Autonomous and Driver controlled modes. You will need to
    // manage all user created tasks if set to false.
    init();
}

/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////

bool driveReverse = false;

/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////

task puncherOn() {
    while (true) {
        puncherSet = 127;
    }
}

task puncherOff() {
    while (true) {
        puncherSet = 0;
    }
}

task intakeOn() {
    while (true) {
        intakeSet = 127;
    }
}

task intakeOff() {
    while (true) {
        intake = 0;
    }
}

void punch() {
    //puncher on
    startTask(puncherOn);
    delayFunc(2000);
    stopTask(puncherOn);
    startTask(puncherOff);
    stopTask(puncherOff);
}

//auton
void auton() {

    //1200 from place to flag or to alliance park
    //2000 from place to center
    punch();

    //intake on
    startTask(intakeOn);

    //intake stop
    stopTask(intakeOn);
    startTask(intakeOff);
    stopTask(intakeOff);

    stopTask(straighten);

}

//////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////

task autonomous() {
    auton();
}

//////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////

string mainBattery, backupBattery;


///////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////

task usercontrol() {

    //display battery voltage
    lcdBattery();

    bLCDBacklight = true;                                    // Turn on LCD Backlight

    while (true) {
        // drive program
        drive();

        // Puncher program
        if (vexRT[Btn6U] == 1) {
            puncherFunc(127);
        } else {
            puncherFunc(0);
        }

        if (vexRT[Btn8U] == 1) {
            auton();
        }

        if (vexRT[Btn7D]) {
            lcdBattery();
        }

        //reverse drive so that you can easily flip caps (find in functions)
        if (vexRT[Btn8D] == 1) {
            if (!driveReverse) {
                waitUntil(vexRT[Btn8D] == 0);
                driveReverse = true;
                delayFunc(500);
            } else if (driveReverse) {
                waitUntil(vexRT[Btn8D] == 0);
                driveReverse = false;
                delayFunc(500);
            }
        }

        // Intake program
        if (vexRT[Btn5U] == 1) {
            intake1Func(127);
            intake2Func(127);
        } else if (vexRT[Btn6D] == 1) {
            intake1Func(-127);
        } else if (vexRT[Btn5D] == 1) {
            intake2Func(-127);
        } else {
            intake1Func(0);
            intake2Func(0);
        }
    }
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////
